export const ORDER_STATUS = {
  pending: { label: 'Pendente', variant: 'warning' },
  in_progress: { label: 'Em andamento', variant: 'info' },
  completed: { label: 'Concluída', variant: 'success' },
  canceled: { label: 'Cancelada', variant: 'error' },
  billed: { label: 'Faturada', variant: 'default' },
};

export const ROLE_LABELS = {
  admin: 'Administrador',
  client: 'Cliente',
  provider: 'Prestador',
};

export const CURRENT_ADMIN = {
  id: 'u5',
  name: 'Thalita Admin',
  firstName: 'Thalita',
  email: 'thalita@ebservices.com',
  phone: '+55 11 94444-5555',
  role: 'admin',
  roleLabel: 'Administradora',
  lastLoginAt: '2026-05-21T08:00:00Z',
};

export const MOCK_USERS = [
  { id: 'u1', name: 'Maria Silva', email: 'maria@example.com', role: 'client', phone: '+55 11 98888-1111', active: true, lastLoginAt: '2026-05-20T09:30:00Z' },
  { id: 'u2', name: 'João Prestador', email: 'joao@example.com', role: 'provider', phone: '+55 11 97777-2222', active: true, lastLoginAt: '2026-05-21T07:15:00Z' },
  { id: 'u3', name: 'Ana Costa', email: 'ana@example.com', role: 'provider', phone: '+55 11 96666-3333', active: false, lastLoginAt: null },
  { id: 'u4', name: 'Carlos Mendes', email: 'carlos@example.com', role: 'client', phone: '+55 11 95555-4444', active: true, lastLoginAt: '2026-05-19T14:00:00Z' },
  { id: 'u5', name: 'Thalita Admin', email: 'thalita@ebservices.com', role: 'admin', phone: '+55 11 94444-5555', active: true, lastLoginAt: '2026-05-21T08:00:00Z' },
];

export const MOCK_PROPERTIES = [
  {
    id: 'p1',
    name: 'Apto Copacabana 402',
    address: 'Av. Atlântica, 1200 — Copacabana, RJ',
    client: 'Maria Silva',
    status: 'active',
    photo: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&h=300&fit=crop',
    icalUrl: 'https://www.airbnb.com/calendar/ical/abc123.ics',
    defaultCleaningPrice: 180,
    latitude: -22.9711,
    longitude: -43.1822,
  },
  {
    id: 'p2',
    name: 'Casa Ipanema Premium',
    address: 'Rua Visconde de Pirajá, 550 — Ipanema, RJ',
    client: 'Carlos Mendes',
    status: 'active',
    photo: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    icalUrl: 'https://www.airbnb.com/calendar/ical/def456.ics',
    defaultCleaningPrice: 250,
    latitude: -22.9838,
    longitude: -43.2096,
  },
  {
    id: 'p3',
    name: 'Studio Leblon 12',
    address: 'Rua Dias Ferreira, 80 — Leblon, RJ',
    client: 'Maria Silva',
    status: 'inactive',
    photo: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=400&h=300&fit=crop',
    icalUrl: null,
    defaultCleaningPrice: 150,
    latitude: null,
    longitude: null,
  },
];

export const MOCK_EXTRAS = [
  { id: 'e1', name: 'Limpeza de Geladeira', defaultPrice: 45, estimatedTime: 30 },
  { id: 'e2', name: 'Limpeza de Vidros', defaultPrice: 60, estimatedTime: 45 },
  { id: 'e3', name: 'Passar Roupa de Cama', defaultPrice: 35, estimatedTime: 20 },
  { id: 'e4', name: 'Limpeza de Forno', defaultPrice: 55, estimatedTime: 40 },
];

export const MOCK_ORDERS = [
  {
    id: 'os1',
    property: 'Apto Copacabana 402',
    propertyAddress: 'Av. Atlântica, 1200',
    provider: 'João Prestador',
    client: 'Maria Silva',
    status: 'in_progress',
    scheduledDate: '2026-05-21',
    startedAt: '2026-05-21T09:00:00Z',
    finishedAt: null,
    basePrice: 180,
    extrasTotalPrice: 45,
    totalPrice: 225,
    checkinLat: -22.9712,
    checkinLong: -43.1823,
    checkoutLat: null,
    checkoutLong: null,
    propertyLat: -22.9711,
    propertyLong: -43.1822,
    beforePhotos: [
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=400&fit=crop',
    ],
    afterPhotos: [],
    extras: [{ name: 'Limpeza de Geladeira', price: 45 }],
  },
  {
    id: 'os2',
    property: 'Casa Ipanema Premium',
    propertyAddress: 'Rua Visconde de Pirajá, 550',
    provider: 'Ana Costa',
    client: 'Carlos Mendes',
    status: 'completed',
    scheduledDate: '2026-05-20',
    startedAt: '2026-05-20T10:00:00Z',
    finishedAt: '2026-05-20T13:30:00Z',
    basePrice: 250,
    extrasTotalPrice: 60,
    totalPrice: 310,
    checkinLat: -22.9839,
    checkinLong: -43.2095,
    checkoutLat: -22.9838,
    checkoutLong: -43.2096,
    propertyLat: -22.9838,
    propertyLong: -43.2096,
    beforePhotos: [
      'https://images.unsplash.com/photo-1560448075-bb485b067938?w=600&h=400&fit=crop',
    ],
    afterPhotos: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600&h=400&fit=crop',
    ],
    extras: [{ name: 'Limpeza de Vidros', price: 60 }],
  },
  {
    id: 'os3',
    property: 'Studio Leblon 12',
    propertyAddress: 'Rua Dias Ferreira, 80',
    provider: null,
    client: 'Maria Silva',
    status: 'pending',
    scheduledDate: '2026-05-22',
    startedAt: null,
    finishedAt: null,
    basePrice: 150,
    extrasTotalPrice: 0,
    totalPrice: 150,
    checkinLat: null,
    checkinLong: null,
    checkoutLat: null,
    checkoutLong: null,
    propertyLat: -22.983,
    propertyLong: -43.224,
    beforePhotos: [],
    afterPhotos: [],
    extras: [],
  },
  {
    id: 'os4',
    property: 'Apto Copacabana 402',
    propertyAddress: 'Av. Atlântica, 1200',
    provider: 'João Prestador',
    client: 'Maria Silva',
    status: 'completed',
    scheduledDate: '2026-05-18',
    startedAt: '2026-05-18T08:30:00Z',
    finishedAt: '2026-05-18T11:00:00Z',
    basePrice: 180,
    extrasTotalPrice: 35,
    totalPrice: 215,
    checkinLat: -22.9711,
    checkinLong: -43.1821,
    checkoutLat: -22.9711,
    checkoutLong: -43.1822,
    propertyLat: -22.9711,
    propertyLong: -43.1822,
    beforePhotos: [
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=600&h=400&fit=crop',
    ],
    afterPhotos: [
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=600&h=400&fit=crop',
    ],
    extras: [{ name: 'Passar Roupa de Cama', price: 35 }],
  },
  {
    id: 'os5',
    property: 'Casa Ipanema Premium',
    propertyAddress: 'Rua Visconde de Pirajá, 550',
    provider: 'Ana Costa',
    client: 'Carlos Mendes',
    status: 'billed',
    scheduledDate: '2026-05-17',
    totalPrice: 250,
  },
  {
    id: 'os6',
    property: 'Studio Leblon 12',
    propertyAddress: 'Rua Dias Ferreira, 80',
    provider: 'João Prestador',
    client: 'Maria Silva',
    status: 'completed',
    scheduledDate: '2026-05-16',
    totalPrice: 185,
  },
  {
    id: 'os7',
    property: 'Apto Copacabana 402',
    propertyAddress: 'Av. Atlântica, 1200',
    provider: 'João Prestador',
    client: 'Maria Silva',
    status: 'canceled',
    scheduledDate: '2026-05-15',
    totalPrice: 180,
  },
  {
    id: 'os8',
    property: 'Casa Ipanema Premium',
    propertyAddress: 'Rua Visconde de Pirajá, 550',
    provider: 'Ana Costa',
    client: 'Carlos Mendes',
    status: 'completed',
    scheduledDate: '2026-05-14',
    totalPrice: 295,
  },
  {
    id: 'os9',
    property: 'Studio Leblon 12',
    propertyAddress: 'Rua Dias Ferreira, 80',
    provider: null,
    client: 'Maria Silva',
    status: 'pending',
    scheduledDate: '2026-05-23',
    totalPrice: 150,
  },
  {
    id: 'os10',
    property: 'Apto Copacabana 402',
    propertyAddress: 'Av. Atlântica, 1200',
    provider: 'João Prestador',
    client: 'Maria Silva',
    status: 'completed',
    scheduledDate: '2026-05-12',
    totalPrice: 220,
  },
  {
    id: 'os11',
    property: 'Casa Ipanema Premium',
    propertyAddress: 'Rua Visconde de Pirajá, 550',
    provider: 'Ana Costa',
    client: 'Carlos Mendes',
    status: 'in_progress',
    scheduledDate: '2026-05-21',
    totalPrice: 310,
  },
  {
    id: 'os12',
    property: 'Studio Leblon 12',
    propertyAddress: 'Rua Dias Ferreira, 80',
    provider: 'João Prestador',
    client: 'Maria Silva',
    status: 'completed',
    scheduledDate: '2026-05-10',
    totalPrice: 165,
  },
];

export const MOCK_INVENTORY_ALERTS = [
  { id: 'a1', property: 'Apto Copacabana 402', item: 'Detergente multiuso', quantity: 2, minQuantity: 5 },
  { id: 'a2', property: 'Casa Ipanema Premium', item: 'Papel higiênico', quantity: 1, minQuantity: 4 },
];

export const BILLING_MONTHS = [
  { value: 0, label: 'Janeiro', short: 'Jan' },
  { value: 1, label: 'Fevereiro', short: 'Fev' },
  { value: 2, label: 'Março', short: 'Mar' },
  { value: 3, label: 'Abril', short: 'Abr' },
  { value: 4, label: 'Maio', short: 'Mai' },
  { value: 5, label: 'Junho', short: 'Jun' },
  { value: 6, label: 'Julho', short: 'Jul' },
  { value: 7, label: 'Agosto', short: 'Ago' },
  { value: 8, label: 'Setembro', short: 'Set' },
  { value: 9, label: 'Outubro', short: 'Out' },
  { value: 10, label: 'Novembro', short: 'Nov' },
  { value: 11, label: 'Dezembro', short: 'Dez' },
];

export const MOCK_BILLING_BY_YEAR = {
  2025: [
    { month: 0, value: 11800 },
    { month: 1, value: 12150 },
    { month: 2, value: 12900 },
    { month: 3, value: 13400 },
    { month: 4, value: 14100 },
    { month: 5, value: 14850 },
    { month: 6, value: 15200 },
    { month: 7, value: 14900 },
    { month: 8, value: 15600 },
    { month: 9, value: 16100 },
    { month: 10, value: 16500 },
    { month: 11, value: 16900 },
  ],
  2026: [
    { month: 0, value: 12400 },
    { month: 1, value: 14200 },
    { month: 2, value: 13800 },
    { month: 3, value: 15600 },
    { month: 4, value: 17250 },
    { month: 5, value: 16800 },
  ],
};

export const MOCK_BILLING_CHART = [
  { month: 'Jan', value: 12400 },
  { month: 'Fev', value: 14200 },
  { month: 'Mar', value: 13800 },
  { month: 'Abr', value: 15600 },
  { month: 'Mai', value: 17250 },
  { month: 'Jun', value: 16800 },
];

export const MOCK_BILLING_REPORT = {
  period: { startDate: '2026-05-01', endDate: '2026-05-31' },
  totalAmount: 17250,
  orderCount: 28,
  clientName: 'Maria Silva',
  orders: MOCK_ORDERS.filter((o) => o.status === 'completed'),
};

export const MOCK_CONTRACT_TEMPLATES = [
  {
    id: 'ct1',
    type: 'client_eb',
    title: 'Contrato EB Services — Limpeza e Manutenção',
    version: '2.1',
    active: true,
    updatedAt: '2026-04-10T12:00:00Z',
    content:
      'Contrato de prestação de serviços de limpeza e manutenção entre o Cliente e EB Services and Solutions, incluindo termos de SLA, confidencialidade e faturamento mensal.',
  },
  {
    id: 'ct2',
    type: 'client_eb',
    title: 'Aditivo — Serviços Extras Premium',
    version: '1.0',
    active: true,
    updatedAt: '2026-05-01T09:30:00Z',
    content:
      'Aditivo contratual para serviços extras premium como limpeza de vidros, geladeira, forno e passadoria de roupa de cama.',
  },
  {
    id: 'ct3',
    type: 'provider_eb',
    title: 'Contrato EB Services — Prestador de Limpeza',
    version: '1.2',
    active: true,
    updatedAt: '2026-03-15T16:00:00Z',
    content:
      'Contrato de prestação de serviços como prestador autônomo vinculado à EB Services, incluindo geofence, fotos obrigatórias e atualização de estoque.',
  },
];

export const MOCK_REVIEWS = [
  {
    id: 'r1',
    orderId: 'os4',
    client: 'Maria Silva',
    provider: 'João Prestador',
    property: 'Apto Copacabana 402',
    rating: 5,
    comment: 'Limpeza impecável, fotos detalhadas e pontualidade excelente.',
    createdAt: '2026-05-18T12:00:00Z',
  },
  {
    id: 'r2',
    orderId: 'os2',
    client: 'Carlos Mendes',
    provider: 'Ana Costa',
    property: 'Casa Ipanema Premium',
    rating: 4,
    comment: 'Bom serviço, pequeno atraso no check-in.',
    createdAt: '2026-05-20T14:30:00Z',
  },
  {
    id: 'r3',
    orderId: 'os10',
    client: 'Maria Silva',
    provider: 'João Prestador',
    property: 'Apto Copacabana 402',
    rating: 5,
    comment: 'Sempre confio no João para preparar o apartamento antes dos hóspedes.',
    createdAt: '2026-05-12T11:15:00Z',
  },
  {
    id: 'r4',
    orderId: 'os8',
    client: 'Carlos Mendes',
    provider: 'Ana Costa',
    property: 'Casa Ipanema Premium',
    rating: 3,
    comment: 'Faltou repor papel higiênico no banheiro social.',
    createdAt: '2026-05-14T18:00:00Z',
  },
];

export const MOCK_PROVIDER_RATINGS = [
  { provider: 'João Prestador', average: 4.8, count: 12 },
  { provider: 'Ana Costa', average: 4.1, count: 9 },
];

export const MOCK_SYNC_LOGS = [
  {
    id: 'sl1',
    property: 'Apto Copacabana 402',
    client: 'Maria Silva',
    icalUrl: 'https://www.airbnb.com/calendar/ical/abc123.ics',
    status: 'success',
    message: '2 novas OS criadas via iCal Airbnb.',
    ranAt: '2026-05-21T06:00:00Z',
  },
  {
    id: 'sl2',
    property: 'Casa Ipanema Premium',
    client: 'Carlos Mendes',
    icalUrl: 'https://www.airbnb.com/calendar/ical/def456.ics',
    status: 'success',
    message: 'Calendário sincronizado sem novas reservas.',
    ranAt: '2026-05-21T06:05:00Z',
  },
  {
    id: 'sl3',
    property: 'Studio Leblon 12',
    client: 'Maria Silva',
    icalUrl: null,
    status: 'error',
    message: 'Link iCal não configurado para este imóvel.',
    ranAt: '2026-05-21T06:10:00Z',
  },
  {
    id: 'sl4',
    property: 'Apto Copacabana 402',
    client: 'Maria Silva',
    icalUrl: 'https://www.airbnb.com/calendar/ical/abc123.ics',
    status: 'error',
    message: 'Falha ao baixar iCal: timeout após 30s.',
    ranAt: '2026-05-20T06:00:00Z',
  },
];
